highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://jwt625.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Wentao Jiang's Resume
name: Wentao Jiang
email: wtjiangthu@gmail.com
email_full: mailto:wtjiangthu@gmail.com
email2: jwt13@mails.tsinghua.edu.cn
email2_full: mailto:jwt13@mails.tsinghua.edu.cn
website: github.io/vitae
website_full: https://jwt625.github.io/vitae
github: jwt625
twitter: jwt0625
linkedin: wentao-jiang-2aa91ba9
tel: +86 13021124165
tel_full: tel:+8613021124165
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: Building 28, Tsinghua University
postcode: 100084
city: Beijing
country: China
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
